spring:
  application:
    name: api_gateway
  config:
    activate:
      on-profile: default

server:
  port: ${SERVER_PORT:8072}

logging:
  level:
    root: DEBUG
    org.springframework.cloud.config: TRACE
    org.springframework.boot.context.config: TRACE
    org.springframework.core.env: TRACE
    org.springframework.web.client: TRACE
    org.springframework.http: TRACE
    org.springframework.web.client.RestTemplate: TRACE
    org.springframework.http.client: DEBUG
    org.apache.http: DEBUG
    org.apache.http.wire: DEBUG
    org.springframework.core.env.PropertySourcesPropertyResolver: TRACE

# information  returned by /actuator/info
info:
  app:
    name: Api Gateway Service (Default)
    version: 1.0.0
    description: Api Gateway Service for Ai news Platform (default profile)

# Eureka client configuration to register with eureka server
eureka:
  instance:
    preferIpAddress: true # register with eureka server with IP address instead of hostname
  client:
    fetchRegistry: true
    registerWithEureka: true # register this service on startup with eureka server
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8070/eureka/}
