spring:
  config:
    activate: 
      on-profile: qa

#  information  returned by /actuator/info
info:
  app:
    name: User Profile Service (QA)
    version: 1.0.0
    description: User Profile Service for Ai news Platform (qa profile)
